name: flutter_boxicons
description: Boxicons (https://boxicons.com) customization for Flutter. You can use 2K+ more Boxicons.
version: 1.0.0
homepage: https://boxicons.com/
repository: https://github.com/Biswajit-Paul-2021/flutter_boxicons.git
issue_tracker: https://github.com/Biswajit-Paul-2021/flutter_boxicons.git
topics:
  - assets
  - icons
  - box-icons

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  http: ^1.2.2

flutter:
  fonts:
    - family: Boxicons          # regular icons
      fonts:
        - asset: fonts/basic/boxicons.ttf
    - family: BoxiconsFilled    # filled icons
      fonts:
        - asset: fonts/filled/boxicons-filled.ttf
    - family: BoxiconsBrands    # brand icons
      fonts:
        - asset: fonts/brands/boxicons-brands.ttf